### ISSUE TITLE
Add a Question template

### ISSUE THREAD

**Issue by plbt5** [nemo-ufes/gufo#19]
**Is your feature request related to a problem? Please describe.**
In order to separate the `features` from `bugs` you've already included two templates. We suggest to insert a third template to distinguish `questions` from the other two.

**Describe the solution you'd like**
Please find below a YAML template for questions. Most importantly, [it](url) prepends "Question: " to the title. Some suggestions are made about formulating a proper question. 

This because we anticipate many questions in our project.

Thanks in advance.

```
name: Question
description: File a question about the use of gUFO
title: "[Question]: your question here"
labels: ["question", "Q&A"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question about gUFO!
  - type: textarea
    id: question
    attributes:
      label: Specify your question
      description: Please describe your question clearly: make assumptions explicit, quote the relevant sentence(s) from our documentation, structure the question by separating the What from the How.
      placeholder: |
        1. What do you want to achieve?
        1. What model did you draft to try to achieve exactly that?
        1. Where did you get stuck and why?
        1. What knowledge do you lack to make progress? 
        1. What is your particular question you need answered? Avoid a yes/no question.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Insert an example
      description: Please add any example code to exemplify your question. It will be turned into code automatically, so no need for backticks.
      render: shell
    validations:
      required: false


```
